In [1]:
number=15

In [2]:
type(number)

int

In [3]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [4]:
my_list=[1,2,3]

In [5]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [6]:
import numpy as np

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
array_a=np.array([1,2,3,4])

In [9]:
array_b=np.array([0, .5, 1, 1.5, 2])

In [10]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
array_a[0]

1

In [13]:
array_b[-1]

2.0

In [14]:
array_a[:2]

array([1, 2])

In [15]:
array_a.dtype

dtype('int32')

In [16]:
array_b.dtype

dtype('float64')

In [17]:
empty_array=np.array([])

In [19]:
empty_array.dtype #Boş olan array'in datatype float'dır.

dtype('float64')

In [22]:
np.array([1,2,3],dtype=np.float_) #float'a çevirme

array([1., 2., 3.])

In [25]:
np.array([1,2,3,4],dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [26]:
array_t=np.array(["ada","lovelace"])

In [27]:
array_t.dtype

dtype('<U8')

Dimensions and Shapes

In [28]:
my_array=np.array([
    [1,2,3],
    [4,5,6]
])

In [29]:
array_a.shape #boyut kontrolü

(4,)

In [30]:
my_array.shape #2 satır üç sütun

(2, 3)

In [31]:
array_a.ndim #boyut kontrolü

1

In [32]:
my_array.ndim

2

In [34]:
my_array.size #elemanlar size

6

In [35]:
my_array=np.array([  # matrislerin tutarlı olması gerekiyor
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [36]:
my_array.ndim

3

In [37]:
my_array.size

12

Indexing and Slicing


In [38]:
my_array=np.array([
     [1,2,3],
     [4,5,6],
     [7,8,9]
])

In [39]:
my_array[1]  #İlk sıradaki row'un tamamını alma

array([4, 5, 6])

In [40]:
my_array[1][0] 

4

In [41]:
my_array[1,0] 

4

In [42]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
my_array[:2,:2] #ilki boyut ikincisi elemanlar

array([[1, 2],
       [4, 5]])

In [47]:
my_array[1]=np.array([10,10,10])

In [48]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [49]:
my_array[2]=90

In [50]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [90, 90, 90]])

In [51]:
my_array[2]=90,92,94

In [52]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [90, 92, 94]])

In [63]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [64]:
my_array=np.arange(1,10)
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# my_array.reshape(5,2)

In [67]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [68]:
np.arange(0,10.1,2)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [72]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [75]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
np.ones([2,5,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [81]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
my_array=np.random.random([5,2])

In [84]:
my_array

array([[0.70270304, 0.45203822],
       [0.00416081, 0.96011669],
       [0.59389345, 0.99964573],
       [0.32630322, 0.63135741],
       [0.69754883, 0.79599191]])

In [89]:
np.random.randint(100, size=[5,5])

array([[95, 26, 45, 36, 21],
       [ 5, 29,  4, 93, 68],
       [19, 77, 68,  7, 85],
       [25, 97, 10, 56, 18],
       [45, 78, 20, 31, 96]])

In [91]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [92]:
# any(), all(), full()

In [93]:
any()

TypeError: any() takes exactly one argument (0 given)

In [97]:
np.any(
   [ [True, False], [True, True]]
)

True

In [98]:
np.all([[True,False],[True,True]])

False

In [102]:
array1 = np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
array1=array1.reshape(2,5)

In [104]:
np.concatenate([array1,array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
np.concatenate([array1,array1],axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

Statistics


In [108]:
array1=np.arange(0,10)
array1=array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [109]:
array1.sum()

45

In [111]:
array1.mean()

4.5

In [112]:
array1.std()

2.8722813232690143

In [113]:
array1.var()

8.25

In [115]:
array1.sum(axis=1)

array([10, 35])

In [116]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [117]:
array1+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [118]:
array1 # Yukarıdaki işlemden orijinal matris etkilenmedi

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [120]:
array1+=10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [121]:
array2=np.arange(0,10)
array2=array2.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [122]:
array2+10
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [123]:
array2=array2+10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

Boolean Arrays

In [125]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [127]:
a[0],a[-1] #ilk ve son elemanlara erişme

(0, 3)

In [128]:
a[[0,-1]] #ilk ve son elemanı array olarak getirme

array([0, 3])

In [129]:
a[[True,False,False,True]] ##Boolean ile eleman alma

array([0, 3])

In [130]:
a>=2

array([False, False,  True,  True])

In [131]:
a[a>=2]

array([2, 3])

In [132]:
a.mean()

1.5

In [133]:
a[a>a.mean()]

array([2, 3])

In [134]:
a[~(a>a.mean())]

array([0, 1])

In [135]:
a[(a==0) | (a==1)]

array([0, 1])

In [136]:
a[(a<=2)&(a%2==0)]

array([0, 2])

In [137]:
# 100'e kadar rastgele tam sayılardan oluşan  olan 3,3  bir matris oluşturur
#30'dan büyük olanları boolean yöntemi ile filtreleyin


In [147]:
rand_array=np.random.randint(100, size=(3,3))
rand_array

array([[49, 63, 18],
       [11, 72,  0],
       [80, 66, 91]])

In [149]:
boolean_array=rand_array>30

In [150]:
boolean_array

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True,  True]])

In [151]:
rand_array[boolean_array]

array([49, 63, 72, 80, 66, 91])

In [155]:
my_array=np.array([0,1,2,3,4,5,6,7,8,9])
array_1=my_array.reshape(5,2)
array_2=my_array.reshape(2,5)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [156]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [157]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [158]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [159]:
array_2.T #yön değiştirme

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [160]:
import sys

In [161]:
sys.getsizeof(10) #int boyutu

28

In [164]:
sys.getsizeof(1000**100)

In [4]:
import numpy as np

In [5]:
np.dtype(int).itemsize

4

In [7]:
np.dtype(float).itemsize

8

In [9]:
np.array([1,2,3]).nbytes

12

In [10]:
my_list=list(range(1000))

In [14]:
my_array=np.arange(100000)

In [15]:
%time np.sum(my_array **2)

Wall time: 0 ns


216474736

In [16]:
%time sum([number **2 for number in my_list])

Wall time: 525 µs


332833500